spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/BaseProy
spring.datasource.username=root
spring.datasource.password=27186627
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# JWT
# JWT (Asegúrate de que no haya espacios al final)
jwt.secret=EstaEsUnaClaveMuyLargaYSeguraParaMiApiDeSodas2026
jwt.expiration=3600000